// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS4f08OJOrZG_JjPOqfx4xROGxeP0cqgA',
    appId: '1:591125634239:web:672ed4dfb080e1efc8ba0a',
    messagingSenderId: '591125634239',
    projectId: 'edumanage-pro-899dc',
    authDomain: 'edumanage-pro-899dc.firebaseapp.com',
    storageBucket: 'edumanage-pro-899dc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlltAtfGqIcl_5B_7OWyylj9CXMnuJyZc',
    appId: '1:591125634239:android:491d887630d504f7c8ba0a',
    messagingSenderId: '591125634239',
    projectId: 'edumanage-pro-899dc',
    storageBucket: 'edumanage-pro-899dc.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS4f08OJOrZG_JjPOqfx4xROGxeP0cqgA',
    appId: '1:591125634239:web:23fed6eee01c80a5c8ba0a',
    messagingSenderId: '591125634239',
    projectId: 'edumanage-pro-899dc',
    authDomain: 'edumanage-pro-899dc.firebaseapp.com',
    storageBucket: 'edumanage-pro-899dc.firebasestorage.app',
  );

}